<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DvsaApplicationLogger\Factory\LoggerFactory' => __DIR__ . '/src/DvsaApplicationLogger/Factory/LoggerFactory.php',
  'DvsaApplicationLogger\Factory\SapiHelperFactory' => __DIR__ . '/src/DvsaApplicationLogger/Factory/SapiHelperFactory.php',
  'DvsaApplicationLogger\Helper\SapiHelper'     => __DIR__ . '/src/DvsaApplicationLogger/Helper/SapiHelper',
  'DvsaApplicationLogger\Formatter\Error'       => __DIR__ . '/src/DvsaApplicationLogger/Formatter/Error.php',
  'DvsaApplicationLogger\Formatter\General'     => __DIR__ . '/src/DvsaApplicationLogger/Formatter/General.php',
  'DvsaApplicationLogger\Formatter\Json'        => __DIR__ . '/src/DvsaApplicationLogger/Formatter/Json.php',
  'DvsaApplicationLogger\Listener\Request'      => __DIR__ . '/src/DvsaApplicationLogger/Listener/Request.php',
  'DvsaApplicationLogger\Listener\Response'     => __DIR__ . '/src/DvsaApplicationLogger/Listener/Response.php',
  'DvsaApplicationLogger\Log\Logger'            => __DIR__ . '/src/DvsaApplicationLogger/Log/Logger.php',
);
